/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SessoesRouteImport } from './routes/sessoes'
import { Route as RumoresRouteImport } from './routes/rumores'
import { Route as PersonagensRouteImport } from './routes/personagens'
import { Route as NpcsRouteImport } from './routes/npcs'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as ArquivoRouteImport } from './routes/arquivo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessoesSlugRouteImport } from './routes/sessoes.$slug'
import { Route as PersonagensSlugRouteImport } from './routes/personagens.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesRoute = SessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RumoresRoute = RumoresRouteImport.update({
  id: '/rumores',
  path: '/rumores',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonagensRoute = PersonagensRouteImport.update({
  id: '/personagens',
  path: '/personagens',
  getParentRoute: () => rootRouteImport,
} as any)
const NpcsRoute = NpcsRouteImport.update({
  id: '/npcs',
  path: '/npcs',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivoRoute = ArquivoRouteImport.update({
  id: '/arquivo',
  path: '/arquivo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesSlugRoute = SessoesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SessoesRoute,
} as any)
const PersonagensSlugRoute = PersonagensSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PersonagensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/notas': typeof NotasRoute
  '/npcs': typeof NpcsRoute
  '/personagens': typeof PersonagensRouteWithChildren
  '/rumores': typeof RumoresRoute
  '/sessoes': typeof SessoesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/personagens/$slug': typeof PersonagensSlugRoute
  '/sessoes/$slug': typeof SessoesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/notas': typeof NotasRoute
  '/npcs': typeof NpcsRoute
  '/personagens': typeof PersonagensRouteWithChildren
  '/rumores': typeof RumoresRoute
  '/sessoes': typeof SessoesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/personagens/$slug': typeof PersonagensSlugRoute
  '/sessoes/$slug': typeof SessoesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arquivo': typeof ArquivoRoute
  '/notas': typeof NotasRoute
  '/npcs': typeof NpcsRoute
  '/personagens': typeof PersonagensRouteWithChildren
  '/rumores': typeof RumoresRoute
  '/sessoes': typeof SessoesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/personagens/$slug': typeof PersonagensSlugRoute
  '/sessoes/$slug': typeof SessoesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arquivo'
    | '/notas'
    | '/npcs'
    | '/personagens'
    | '/rumores'
    | '/sessoes'
    | '/sitemap.xml'
    | '/personagens/$slug'
    | '/sessoes/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arquivo'
    | '/notas'
    | '/npcs'
    | '/personagens'
    | '/rumores'
    | '/sessoes'
    | '/sitemap.xml'
    | '/personagens/$slug'
    | '/sessoes/$slug'
  id:
    | '__root__'
    | '/'
    | '/arquivo'
    | '/notas'
    | '/npcs'
    | '/personagens'
    | '/rumores'
    | '/sessoes'
    | '/sitemap.xml'
    | '/personagens/$slug'
    | '/sessoes/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArquivoRoute: typeof ArquivoRoute
  NotasRoute: typeof NotasRoute
  NpcsRoute: typeof NpcsRoute
  PersonagensRoute: typeof PersonagensRouteWithChildren
  RumoresRoute: typeof RumoresRoute
  SessoesRoute: typeof SessoesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes': {
      id: '/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof SessoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rumores': {
      id: '/rumores'
      path: '/rumores'
      fullPath: '/rumores'
      preLoaderRoute: typeof RumoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personagens': {
      id: '/personagens'
      path: '/personagens'
      fullPath: '/personagens'
      preLoaderRoute: typeof PersonagensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/npcs': {
      id: '/npcs'
      path: '/npcs'
      fullPath: '/npcs'
      preLoaderRoute: typeof NpcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivo': {
      id: '/arquivo'
      path: '/arquivo'
      fullPath: '/arquivo'
      preLoaderRoute: typeof ArquivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes/$slug': {
      id: '/sessoes/$slug'
      path: '/$slug'
      fullPath: '/sessoes/$slug'
      preLoaderRoute: typeof SessoesSlugRouteImport
      parentRoute: typeof SessoesRoute
    }
    '/personagens/$slug': {
      id: '/personagens/$slug'
      path: '/$slug'
      fullPath: '/personagens/$slug'
      preLoaderRoute: typeof PersonagensSlugRouteImport
      parentRoute: typeof PersonagensRoute
    }
  }
}

interface PersonagensRouteChildren {
  PersonagensSlugRoute: typeof PersonagensSlugRoute
}

const PersonagensRouteChildren: PersonagensRouteChildren = {
  PersonagensSlugRoute: PersonagensSlugRoute,
}

const PersonagensRouteWithChildren = PersonagensRoute._addFileChildren(
  PersonagensRouteChildren,
)

interface SessoesRouteChildren {
  SessoesSlugRoute: typeof SessoesSlugRoute
}

const SessoesRouteChildren: SessoesRouteChildren = {
  SessoesSlugRoute: SessoesSlugRoute,
}

const SessoesRouteWithChildren =
  SessoesRoute._addFileChildren(SessoesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArquivoRoute: ArquivoRoute,
  NotasRoute: NotasRoute,
  NpcsRoute: NpcsRoute,
  PersonagensRoute: PersonagensRouteWithChildren,
  RumoresRoute: RumoresRoute,
  SessoesRoute: SessoesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
